"""empty message

Revision ID: affba0ad57fd
Revises: a858a1abf5a4
Create Date: 2020-12-21 22:59:44.285574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affba0ad57fd'
down_revision = 'a858a1abf5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_title_key', 'movies', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('movies_title_key', 'movies', ['title'])
    # ### end Alembic commands ###
